version: "3"
services:
  rabbitmq:
    image: rabbitmq:management-alpine
    env_file:
      - ./resources/.env
    ports:
      - "15672:15672"
      - "5672:5672"
  telegraf:
    image: telegraf
    volumes:
      - ./resources/docker/telegraf.conf:/etc/telegraf/telegraf.conf:rw
    links:
      - influx
      - rabbitmq
  influx:
    image: influxdb
    volumes:
      - ./resources/docker/influx:/var/lib/influxdb
  grafana:
    image: grafana/grafana
    environment:
      - "GF_SERVER_ROOT_URL=http://grafana.server.name"
      - "GF_SECURITY_ADMIN_PASSWORD=queenelizabeth"
    ports:
      - "3000:3000"
    volumes:
      - ./resources/docker/grafana_storage:/var/lib/grafana
    depends_on:
      - influx
  mongodb:
    image: mongo:latest
    expose:
      - 27017
    ports:
      - "27017:27017"
  master:
    build: ./resources/pyspark/.
    command: bin/spark-class org.apache.spark.deploy.master.Master -h master
    hostname: master
    environment:
      MASTER: spark://master:7077
      SPARK_PUBLIC_DNS: localhost
    expose:
      - 8080
      - 7077
    ports:
      - 8080:8080
      - 7077:7077
    links:
      - mongodb
    volumes:
      - ./resources/docker/mongodb:/data/db
  worker:
    build: ./resources/pyspark/.
    command: bin/spark-class org.apache.spark.deploy.worker.Worker spark://master:7077
    hostname: worker
    environment:
      SPARK_WORKER_CORES: 2
      SPARK_WORKER_MEMORY: 2g
      SPARK_WORKER_PORT: 8881
      SPARK_WORKER_WEBUI_PORT: 8081
      SPARK_PUBLIC_DNS: localhost
    links:
      - master
    expose:
      - 8881
    ports:
      - 8081:8081
